spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/panjiao_shop?useSSL=true&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10000
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
logging:
  config: classpath:log4j2-spring.xml
